const SHADOW_THRESHOLD = 20;
const CATCH_THRESHOLD = 5;
const GAME_DURATION = 900;
const SECOND = 1000;
const SYNC_DELAY = 30;

module.exports = {
    SHADOW_THRESHOLD,
    CATCH_THRESHOLD,
    GAME_DURATION,
    SECOND,
    SYNC_DELAY
}